#!/usr/bin/env node
/**
 * Local playground.
 *
 *   npm run playground
 *
 * Bundles playground/app.jsx with esbuild, aliasing `use-theme-mode` to the
 * built ESM output, and serves it. Nothing here touches src/ — this exercises
 * the same files npm publish uploads, which is the point of a pre-publish
 * smoke test.
 */
import { build } from "esbuild";
import { createServer } from "node:http";
import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, extname, join, normalize, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "playground", ".out");
const distEntry = join(root, "dist", "index.mjs");
const port = Number(process.env.PORT) || 5180;

if (!existsSync(distEntry)) {
  console.error(
    "\ndist/index.mjs is missing. Run `npm run build` first, or use `npm run playground` which builds for you.\n"
  );
  process.exit(1);
}

// themeScript comes from the built bundle too, so the pre-paint script and
// the runtime are generated by the same code that ships.
const { themeScript } = await import(`file://${distEntry}`);
const { playgroundOptions } = await import(
  `file://${join(root, "playground", "options.mjs")}`
);

await mkdir(outDir, { recursive: true });

await build({
  entryPoints: [join(root, "playground", "app.jsx")],
  outfile: join(outDir, "app.js"),
  bundle: true,
  format: "esm",
  target: "es2020",
  jsx: "automatic",
  sourcemap: true,
  logLevel: "info",
  define: { "process.env.NODE_ENV": '"development"' },
  alias: { "use-theme-mode": distEntry },
});

const template = await readFile(
  join(root, "playground", "index.template.html"),
  "utf8"
);

const html = template.replace(
  "<!--THEME_SCRIPT-->",
  `<script>${themeScript(playgroundOptions)}</script>`
);

await writeFile(join(outDir, "index.html"), html);

// Same page, React removed, inline pre-paint script kept. This isolates the
// one question DevTools' "Disable JavaScript" cannot answer, because that
// blocks the inline script too.
const htmlWithoutReact = html.replace(
  /<script type="module"[^>]*><\/script>/,
  '<p data-no-react style="max-width:760px;margin:0 auto;padding:16px;border:1px solid var(--line);border-radius:10px;font:14px/1.6 ui-sans-serif,system-ui,sans-serif">' +
  "React was not loaded on this page. Only the inline pre-paint script ran. " +
  "If the colours around this box match your saved theme, the no-flash script works." +
  "</p>"
);

const MIME = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".map": "application/json; charset=utf-8",
  ".css": "text/css; charset=utf-8",
};

const server = createServer(async (req, res) => {
  const [rawPath, query = ""] = (req.url ?? "/").split("?");
  const requested = decodeURIComponent(rawPath);
  const relative = requested === "/" ? "/index.html" : requested;

  if (relative === "/index.html" && new URLSearchParams(query).has("no-react")) {
    res.writeHead(200, {
      "Content-Type": "text/html; charset=utf-8",
      "Cache-Control": "no-store",
    });
    res.end(htmlWithoutReact);
    return;
  }

  const file = normalize(join(outDir, relative));

  // Refuse anything that escapes the output directory.
  if (!resolve(file).startsWith(resolve(outDir))) {
    res.writeHead(403).end("Forbidden");
    return;
  }

  try {
    const body = await readFile(file);
    res.writeHead(200, {
      "Content-Type": MIME[extname(file)] ?? "application/octet-stream",
      "Cache-Control": "no-store",
    });
    res.end(body);
  } catch {
    res.writeHead(404).end("Not found");
  }
});

server.on("error", (error) => {
  if (error.code === "EADDRINUSE") {
    console.error(
      `\nPort ${port} is already in use. Either stop the other process, or pick another port:\n\n  PORT=5199 npm run playground\n\n  PowerShell:  $env:PORT=5199; npm run playground\n`
    );
    process.exit(1);
  }
  throw error;
});

server.listen(port, () => {
  console.log(`
  Playground running against dist/

    http://localhost:${port}

  Seven checks are listed on the page. The no-flash proof:

    http://localhost:${port}/?no-react

  Do NOT use DevTools "Disable JavaScript" — it blocks the inline script
  too, so you get a blank page that proves nothing.

  Ctrl+C to stop.
`);
});
